version: '3.8'

services:
  # 本地 Supabase (通过 CLI 管理)
  supabase-setup:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        npm install -g supabase &&
        supabase start &&
        echo 'Supabase started successfully' &&
        tail -f /dev/null
      "
    ports:
      - "54321:54321"  # API
      - "54322:54322"  # DB
      - "54323:54323"  # Studio
    environment:
      - NODE_ENV=development

  # Upstash Redis (开发环境用本地 Redis)
  redis-dev:
    image: redis:7.2-alpine
    container_name: vue-express-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  # Express 后端
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: vue-express-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      REDIS_URL: redis://redis-dev:6379
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - redis-dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Vue3 前端
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vue-express-frontend-dev
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:5000/api
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  redis_dev_data:
    driver: local

networks:
  default:
    name: vue-express-dev