[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend"

[services.variables]
NODE_ENV = "production"

[[services]]
name = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "5000"

[[services]]
name = "mongodb"
image = "mongo:7.0"

[services.variables]
MONGO_INITDB_ROOT_USERNAME = "admin"
MONGO_INITDB_ROOT_PASSWORD = "password"

[[services]]
name = "redis"
image = "redis:7.2-alpine"