services:
  # 前端静态网站
  - type: web
    name: vue-express-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://vue-express-backend.onrender.com/api
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

  # 后端 API 服务
  - type: web
    name: vue-express-backend
    env: node
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: vue-express-mongodb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: vue-express-redis
          property: connectionString

  # MongoDB 数据库
  - type: pserv
    name: vue-express-mongodb
    env: docker
    dockerfilePath: ./Dockerfile.mongodb
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 1

  # Redis 缓存
  - type: redis
    name: vue-express-redis
    plan: starter